contact_links:
  - name: Discord Support
    url: https://discord.gg/6R4DK4G5Zh
    about: For real-time help and discussions
  - name: GitHub Discussions
    url: https://github.com/react-chatbotify/react-chatbotify/discussions
    about: For questions and ideas
